name: cyg

on:
  push:
    branches: [ develop ]

jobs:
  test:
    name: "cyg"  
    runs-on: windows-latest
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf input

      - uses: actions/checkout@v4

      - name: Install Cygwin
        uses: cygwin/cygwin-install-action@master
        with:
          packages: cmake gcc-fortran make ninja perl zlib-devel
      - name: Test HDF5
        run: |
          export PATH=/usr/bin:$PATH
          mkdir build
          cd build
          which cmake
          cmake -G Ninja \
           -D BUILD_SHARED_LIBS:BOOL=OFF \
           -D CTEST_DROP_SITE_INIT:STRING="my.cdash.org" \
           -D SITE:STRING=cwin ..
          ctest -T Build
          ctest -T Test
          if [[ $? -ne 0 ]]; then
            ctest -T Submit
          fi
        shell: C:\cygwin\bin\bash.exe -eo pipefail -o igncr '{0}'
