name: mac ninja clang h f j mpich

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        name: ["macOS Latest Clang"]
        include:
          - name: "macOS Latest Clang"
            artifact: "macOS.tar.xz"
            os: macos-latest
            build_type: "Release"
            cpp: OFF
            fortran: ON
            java: ON
            ts: OFF
            hl: ON
            parallel: ON
            toolchain: "config/toolchain/clang.cmake"
            generator: "-G Ninja"

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'skip-ci')"

    steps:
    - name: Install Dependencies (macOS)
      run: brew install ninja mpich libaec
      if: matrix.os == 'macos-latest'

    - name: Install gfortran
      uses: awvwgk/setup-fortran@v1

    - name: Get Sources
      uses: actions/checkout@v4.1.1

    - name: Configure
      run: |
        which gfortran
        export FC="$(which gfortran)"
        mkdir "${{ runner.workspace }}/build"
        cd "${{ runner.workspace }}/build"
        cmake ${{ matrix.generator }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_TOOLCHAIN_FILE=${{ matrix.toolchain }} -DBUILD_SHARED_LIBS=ON -DHDF5_ENABLE_ALL_WARNINGS=ON -DHDF5_ENABLE_THREADSAFE:BOOL=${{ matrix.ts }} -DHDF5_BUILD_HL_LIB:BOOL=${{ matrix.hl }} -DHDF5_ENABLE_PARALLEL:BOOL=${{ matrix.parallel }} -DHDF5_BUILD_CPP_LIB:BOOL=${{ matrix.cpp }} -DHDF5_BUILD_FORTRAN=${{ matrix.fortran }} -DHDF5_BUILD_JAVA=${{ matrix.java }} -DMPIEXEC_MAX_NUMPROCS:STRING=3 -DHDF5_ENABLE_SZIP_SUPPORT:BOOL=OFF $GITHUB_WORKSPACE
      shell: bash

    - name: Build
      if: matrix.generator != 'autogen'
      run: cmake --build . --config ${{ matrix.build_type }}
      working-directory: ${{ runner.workspace }}/build

    - name: Test
      if: matrix.generator != 'autogen'
      run: ctest --build . -C ${{ matrix.build_type }} -V -E MPI_TEST_H5DIFF-h5diff
      working-directory: ${{ runner.workspace }}/build

    - name: Upload
      if: matrix.generator != 'autogen'
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: ${{ runner.workspace }}/build/Testing/Temporary/CTestCostData.txt
