name: mac14 ninja h j ompi cd

on: [push, pull_request]

jobs:
  build:
    name: "mac14 ninja h j ompi cd"
    runs-on: macos-14
    steps:
    - name: Install Dependencies
      run: brew install ninja openmpi libaec

    - name: Get Sources
      uses: actions/checkout@v4.1.1

    - name: Test
      run: |
        mkdir build
        cd build
        cmake -G Ninja \
        -D BUILD_SHARED_LIBS=ON \
        -D CTEST_DROP_SITE_INIT:STRING="my.cdash.org" \
        -D HDF5_BUILD_HL_LIB:BOOL=ON \
        -D HDF5_BUILD_JAVA=ON \
        -D HDF5_ENABLE_ALL_WARNINGS=ON \
        -D HDF5_ENABLE_PARALLEL:BOOL=ON \
        -D HDF5_ENABLE_SZIP_SUPPORT:BOOL=OFF \
        -D MPIEXEC_MAX_NUMPROCS:STRING=2 \
        -D SITE:STRING=mac14 \
        ..
        ctest -T Build --output-on-error -j
        ctest -T Test --output-on-error -j
        if [[ $? -ne 0 ]]; then
          ctest -T Submit
        fi
      shell: bash
