name: nbsd f sh

on: [push, pull_request]

jobs:
  test:
    name: nbsd f sh
    runs-on: ${{ matrix.os.host }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: netbsd
            architecture: x86-64
            version: '9.3'
            host: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ${{ matrix.os.name }}
        uses: cross-platform-actions/action@v0.23.0
        env:
          FOO: A
          BAR: B
        with:
          environment_variables: FOO BAR
          operating_system: ${{ matrix.os.name }}
          architecture: ${{ matrix.os.architecture }}
          version: '${{ matrix.os.version }}'
          shell: bash
          run: |
            sudo pkgin -y install cmake
            sudo pkgin -y install gcc7
            sudo pkgin -y install git
            sudo pkgin -y install mozilla-rootcerts
            sudo pkgin -y install mozilla-rootcerts-openssl
            export LD_LIBRARY_PATH=/usr/pkg/lib
            export FC=/usr/pkg/gcc7/bin/gfortran
            mkdir build
            cd build
            cmake \
            -DBUILDNAME:STRING="f.-sh" \
            -DBUILD_SHARED_LIBS:BOOL=OFF \
            -DCTEST_DROP_SITE_INIT:STRING="my.cdash.org" \
            -DHDF5_BUILD_FORTRAN:BOOL=ON \
            -DSITE:STRING=nbsd ..
            ctest -D Experimental
