name: riscv64 lin

on: [push, pull_request]

jobs:
  riscv64_job:
    # The host should always be Linux
    runs-on: ubuntu-latest
    name: Build on ubuntu-latest riscv64
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: riscv64
          distro: ubuntu_latest
          install: |
            apt-get update -q -y
            apt-get install -q -y git
            apt-get install -q -y cmake
          run: |
            mkdir build
            cd build
            cmake -DHDF5_ENABLE_SZIP_SUPPORT:BOOL=OFF ..
            make
            make test
